### ISSUE TITLE
Report HTML Azure-pipelines lighthouse  - THE REPORT DOES NOT WORK

### ISSUE THREAD

**Issue by mpuertao** [GuruCharan94/azure-devops-extensions#23]
Hello @GuruCharan94 .

The report HTML  in azure pipelines does not work with the extension Lighthouse-CI

![image](https://user-images.githubusercontent.com/33495827/117734531-4505b480-b1b9-11eb-839e-89731fb45f1b.png)

Config task lighthouse-ci:

![image](https://user-images.githubusercontent.com/33495827/117734894-03c1d480-b1ba-11eb-8cac-447855cda198.png)

Add lighthouserc.json:

```json
{
    "ci": {
        "collect": {
            "chromePath": false,
            "numberOfRuns": 3,
            "url": "https://www.google.com.co"
        },
        "assert": {
            "assertions": {
                "categories:performance": ["error", { "minScore": 0.10 }],
                "categories:accessibility": ["error", { "minScore": 0.7 }],
                "categories:best-practices": ["error", { "minScore": 0.5 }],
                "categories:seo": ["error", { "minScore": 0.80 }]
            }
        }
    }
}
```

<br>
<br>

You can recommend me how I can generate the report, similar to the one generated by google's lighthouse:

<br>

![image](https://user-images.githubusercontent.com/33495827/117734762-bfcecf80-b1b9-11eb-87e1-5cdc734d0131.png)

Thanks, best regards

**Comment by GuruCharan94** [comment]
Hi, Thanks for trying out the extensions. :)

The lighthouse and lighthouse ci are separate extensions. Currently, 
- The lighthouse extensions embeds the report inside Azure DevOps.
- The lighthouse-ci extension requires that you upload the results to a [lighthouse server that you have to set up](https://www.gurucharan.in/web/nodejs/lighthouse-ci-the-complete-guide-part-2/)

I like the idea that the lighthouse-ci extension should also embed reports of the current run inside Azure DevOps. 
I will keep the issue open and might work on it in the future. As of now, I can't provide you an estimate on when this functionality will be available. PR's welcome.

Thanks.

**Comment by mpuertao** [comment]
Thank you very much, stay tuned, and thank you very much for the extensions

**Comment by snehadominic** [comment]
Hey @GuruCharan94, this will be a great feature to have, if the HTML reports can be added as an attachment of the build / release so that it can be directly downloaded from logs. Also, thanks for the extension.

@mpuertao , Can you please share the approach you've used to obtain the HTML reports? Is there any alternative that we can follow, instead of setting up a lighthouse server and uploading results to that.

**Comment by GuruCharan94** [comment]
Some work arounds I can think of is [configuring the upload target to filesystem](https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/configuration.md#upload) and 
1. Publish the contents of the target folder as build artifacts if using the extension in a build. 
2. Since artifacts are not supported in a release, copy the reports to the blob storage services from a cloud provider (Storage Account/ S3 etc.) if you are using the cloud.

**Comment by snehadominic** [comment]
@GuruCharan94 , Thanks for the options. We are using the scan on release pipelines, hence option1 is not possible. Also, I was trying to get the report without using any additional azure services, as it is already present in the agent. As you said, publishing artifacts in release pipelines not being supported is a blocker now.

**Comment by snehadominic** [comment]
Hi @GuruCharan94 , Right now, we are trying to write the files to filesystem. Is there any option available to customize the names of scan report? Please let me know the steps, if available.

**Comment by mpuertao** [comment]
Hello @snehadominic . For now i am using Google LightHouse. Generate Report
![image](https://user-images.githubusercontent.com/33495827/122995766-a059c380-d36f-11eb-8b8b-3c17d286ac45.png)

**Comment by GuruCharan94** [comment]
The lighthouse extension allows embed of results inside Azure Devops.
The lighthouse CI extensions requires that you store results on storage outside of Azure Devops. There is no plan to get the lighthouse CI extension to support embedding of results. 

Closing.
